baseURL = "https://LaneyYu.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "LaneyYu"
# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "yu"

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[params]
title = "I'm Laney"
author = "LaneyYu"
description = """
a freshman
---
"""
profilePicture = "images/profile.jpeg"



[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "534013339@qq.com"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80


